---
{
    "name": "CI",
    "on": [
        "push",
        "pull_request"
    ],
    "jobs": {
        "Scalafmt": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Formatting",
                    "run": "./bin/scalafmt --test"
                }
            ]
        },
        "Scalafix": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Linting",
                    "run": "csbt scalafixCheck githubActionsCheck"
                }
            ]
        },
        "Docusaurus": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Website",
                    "run": "csbt docs/docusaurusCreateSite"
                }
            ]
        }
    }
}