name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Formatting
        run: ./bin/scalafmt --test
      - name: Scalafix
        run: csbt scalafixCheck
      - name: Documentation
        run: csbt docs/docusaurusCreateSite
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - "slow/testOnly tests.sbt"
          - "slow/testOnly tests.mill"
          - "slow/testOnly tests.gradle"
          - "slow/testOnly tests.maven"
          - "slow/testOnly tests.feature"
          - "unit/test"
          - "+cross/test"
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Compile
        run: csbt '${{ matrix.command }}'
