name: CI
on: [push, pull_request]
jobs:
  Scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Formatting
        run: ./bin/scalafmt --test
  Scalafix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Linting
        run: csbt scalafixCheck
  Docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Website
        run: csbt docs/docusaurusCreateSite
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [sbt, mill, gradle, maven, feature]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Run command
        run: csbt 'slow/testOnly -- tests.${{ matrix.tool }}'
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - "unit/test"
          - "+cross/test"
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Run command
        run: csbt ${{ matrix.command }}
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        command:
          - "unit/test"
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Run command
        run: java -jar sbt-launch.jar ${{ matrix.command }}

