---
{
   "jobs": {
      "Scalafmt": {
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "uses": "actions/checkout@v1"
            },
            {
               "uses": "olafurpg/setup-scala@v2"
            },
            {
               "name": "Formatting",
               "run": "./bin/scalafmt --test"
            }
         ]
      }
   },
   "name": "CI",
   "on": [
      "push",
      "pull_request"
   ]
}
...
