name: CI
on: [push, pull_request]
jobs:
  Scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Formatting
        run: ./bin/scalafmt --test
  Scalafix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Linting
        run: csbt scalafixCheck
  Docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Website
        run: csbt docs/docusaurusCreateSite
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [sbt, mill, gradle, maven, feature]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Run command
        run: csbt 'slow/testOnly -- tests.${{ matrix.tool }}'
  PresentationCompiler:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - "2.13.0"
          - "2.12.8"
          - "2.12.9"
          - "2.12.10"
          - "2.12.7"
          - "2.11.12"
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Cross tests
        run: csbt ++${{ matrix.scala }} cross/test
  Metals:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - '{ansi,applyedit,bsp,builds,codelens}'
          - '{compile,completions,metals,definition,documenthighlight}'
          - '{documentsymbol,filewatch,foldingrange,formatting,hover}'
          - '{http,mtags,references,statusbar,tvp,workspacesymbol}'
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Run command
        run: csbt 'unit/testOnly -- tests.${{ matrix.command }}'
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        command:
          - "unit/test"
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Run command
        run: java -jar sbt-launch.jar ${{ matrix.command }}

