---
{
    "name": "CI",
    "on": [
        "push",
        "pull_request"
    ],
    "jobs": {
        "Metals": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Run tests",
                    "run": "csbt 'unit/testOnly -- tests.${{ matrix.test }}'"
                }
            ],
            "strategy": {
                "fail-fast": false,
                "matrix": {
                    "test": [
                        "{ansi,applyedit,bsp}",
                        "{builds,codelens,compile}",
                        "{completions,definition,documenthighlight}",
                        "{documentsymbol,filewatch,foldingrange}",
                        "{formatting,hover,http}",
                        "{metals,mtags,references}",
                        "{statusbar,tvp,workspacesymbol}"
                    ]
                }
            }
        },
        "Mtags": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Run tests",
                    "run": "csbt ++${{  matrix.scala }} cross/test"
                }
            ],
            "strategy": {
                "fail-fast": false,
                "matrix": {
                    "scala": [
                        "2.13.0",
                        "2.13.1",
                        "2.12.8",
                        "2.12.9",
                        "2.12.10",
                        "2.12.7",
                        "2.11.12"
                    ]
                }
            }
        },
        "Build": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Run tests",
                    "run": "csbt 'slow/testOnly -- tests.${{ matrix.test }}'"
                }
            ],
            "strategy": {
                "fail-fast": false,
                "matrix": {
                    "test": [
                        "feature",
                        "gradle",
                        "maven",
                        "mill",
                        "sbt"
                    ]
                }
            }
        },
        "Scalafmt": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Run Scalafmt",
                    "run": "./bin/scalafmt --test"
                }
            ]
        },
        "Scalafix": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Run Scalafix",
                    "run": "csbt scalafixCheck"
                }
            ]
        },
        "Miscellaneous": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v1"
                },
                {
                    "uses": "olafurpg/setup-scala@v2"
                },
                {
                    "name": "Run Scalafix",
                    "run": "csbt scalafixCheck"
                },
                {
                    "name": "Generate Website",
                    "run": "csbt docs/docusaurusCreateSite"
                },
                {
                    "name": "Check Build Matrix",
                    "run": "csbt githubActionsCheck"
                }
            ]
        }
    }
}